services:
  postgres-opticon:
    image: postgres:16
    environment:
      POSTGRES_DB: "model"
      POSTGRES_USER: "model"
      POSTGRES_PASSWORD: "model"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/model/postgresql/data
    command: |
      postgres
      -c wal_level=logical
      -c max_wal_senders=5
      -c max_replication_slots=5
volumes:
  postgres_data:
    driver: local