steps:
    - label: ":docker: Build"
      plugins:
          - docker-compose#v3.0.0:
                build: app
                push: app

    - wait
    - label: "Run tests"
      command: ./test.sh
      plugins:
          - docker-compose#v3.0.0:
                run: app
